name: LiveProspect Blog
markdown: redcarpet
permalink: /:year-:month-:day-:title
prose:
  rooturl: '_posts'
  siteurl: 'http://liveprospect.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post

